name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
    tags:     [ "*" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/boldrqwe/instructions_front
  VITE_API_BASE_URL: https://site.79.174.84.176.sslip.io/api/v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/boldrqwe/instructions_front
          tags: |
            type=sha,format=short,prefix=sha-
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
